### ISSUE TITLE
Bug: Space Cannon Defense should not generate a Sardakk Mech hit

### ISSUE THREAD

**Issue by SephHawkins** [pgsandstrom/ti4calc#12]
**Sardakk Mech**: After this unit uses its SUSTAIN DAMAGE ability during Ground Combat, it produces 1 hit against your opponent's ground forces on this planet.

Since Space Cannon Defense is a separate step from Ground Combat, if the Mech sustains during Space Cannon Defense, it shouldn't generate a hit. It looks like the calculator is generating a hit in this case.

As an example:

### Sardakk Mech vs. generic PDS + Infantry

The calculator lists this as 100% chance for Sardakk to win. Based on the math, it should be:

- ~80% chance to win (PDS misses, or PDS hits and Mech gets a hit before Infantry)
- ~12% chance to draw (PDS hits, Mech and Infantry get a hit at the same time)
- ~8% chance to lose (PDS hits, Infantry gets a hit before Mech)

**Comment by pgsandstrom** [comment]
Really nice find! This community is insane at finding and reporting bugs :)

I just released a fix that should correct this. Reference fight:

https://ti4battle.com/?attacker-faction=Sardakk+N%27orr&attacker-unit-mech=1&defender-faction=Creuss&defender-unit-infantry=1&defender-unit-pds=1&place=Ground

Let me know if you run into any other issues!
