### ISSUE TITLE
Cavalry promissory note is incorrect

### ISSUE THREAD

**Issue by ben-phillips** [pgsandstrom/ti4calc#13]
Scenario: Battle simulation in the screenshot below.

Non-nomad faction: 
  1 carrier
  Cavalry (memoria I) promissory note
vs. 
Nomad: 
  Memoria I

Expected: 
1) Cavalry not applied, because battle is against Nomad
2) the results should be evenly matched

Actual
1) Cavalry is applied
2) Non-nomad faction wins

Looks like the promissory note is giving an extra die roll (e.g. Memoria I is using 7x3 instead of 7x2). PR incoming

<img width="501" alt="image" src="https://github.com/pgsandstrom/ti4calc/assets/20345381/31c6cfc6-32fb-4bca-b81d-354eb12fda1a">

**Comment by pgsandstrom** [comment]
Awesome bug report, and even better PR! I have deployed the fix. Thank you! :)
