### ISSUE TITLE
Is "Nekro mech bonus" broken?

### ISSUE THREAD

**Issue by brianwawok** [pgsandstrom/ti4calc#7]
I cannot get it to change my results...  try 1 mech vs 2 infantry.  On vs off is no change.  Pretty sure +2 to hit should do SOMETHING?

**Comment by brianwawok** [comment]
In nekro.ts line 49

if I log "p", it has a

```
 "effects": {
    "Nekro mech bonus": 1
  },
```
  
  but if I log `p.effects` it is undefined.  Not sure what this means

**Comment by brianwawok** [comment]
Looks like we are setting the effects AFTER we are calling our transformUnit method

**Comment by brianwawok** [comment]
battlesetup.ts

we are transforming on line 255

We are setting on line 263.. the set is after the transform...

**Comment by pgsandstrom** [comment]
Great find! I'll have a look at it as soon as possible.

**Comment by pgsandstrom** [comment]
I had written the nekro.ts file in an unnecessarily complicated way that resultet in a bug. The new simpler version is worked as intended:

https://ti4battle.com/?attacker-faction=Barony+of+Letnev&attacker-unit-mech=2&defender-faction=Nekro&defender-unit-mech=2&defender-effect-Nekro+mech+bonus=1&place=Ground

Thank you for the great bug report!

**Comment by brianwawok** [comment]
> I had written the nekro.ts file in an unnecessarily complicated way that resultet in a bug. The new simpler version is worked as intended:

Awesome, thanks for sorting it out!  I was hoping to be able to get all the way to PR, but lost steam along the way. Glad having my ramblings was enough to reproduce ;)
