### ISSUE TITLE
Dreadnoughts II should always sustain, even if "Risk Direct Hit" is unchecked.

### ISSUE THREAD

**Issue by bradleysigma** [pgsandstrom/ti4calc#9]
Since Dreadnoughts II cannot be destroyed by Direct Hits, then they should completely ignore the "Risk Direct Hit" setting and always sustain. In addition, they should probably sustain preferentially over other unit types, which would probably be most relevant to Sol and Ul with their upgraded carriers and cruisers, respectively.

**Comment by pgsandstrom** [comment]
It should already work like you say. The line that controls this is right here:

https://github.com/pgsandstrom/ti4calc/blob/b1adb26d48970ca8b099e4abe0f16ad93dfc2fe5/core/battle.ts#L506

It can also be seen in battles such as this:

http://localhost:3000/?attacker-faction=Creuss&attacker-unit-dreadnought=2&attacker-unit-carrier=1&defender-faction=Creuss&defender-unit-dreadnought=2&defender-unit-carrier=1&defender-risk-direct-hit=false&defender-upgrade-dreadnought=true

One side has "risk direct hit" and the other have dreadnought upgrade. It gives the same effect to the battle.

**Comment by bradleysigma** [comment]
Hmmmm, I think I was just confused by the detailed results table e.g. (from [this battle](https://ti4battle.com/?attacker-faction=Barony+of+Letnev&attacker-unit-flagship=1&attacker-unit-warsun=1&attacker-unit-dreadnought=2&attacker-risk-direct-hit=false&attacker-upgrade-dreadnought=true&attacker-effect-Duranium+Armor=1&defender-faction=Barony+of+Letnev&defender-unit-flagship=1&defender-unit-warsun=1&defender-unit-dreadnought=2&defender-upgrade-dreadnought=true&defender-effect-Duranium+Armor=1):
![image](https://github.com/pgsandstrom/ti4calc/assets/42644678/d3d51885-88e3-4561-b4f9-1a1ad6c92c77)
In particular, for the defender, the results aren't primarily ordered by the number of remaining ships, but instead primarily ordered by the damage condition of the war sun. To me, it would make more sense for the output to look like:
```
Draw W- W+ W- W+ W- W+ W- W+ W- W+ W- W+
           F+ F+ F+ F+ F+ F+ F+ F+ F+ F+
                 D- D- D+ D+ D- D- D+ D+
                             D- D- D- D-
```

**Comment by pgsandstrom** [comment]
You're right, that looks weird. I'll have a look at it.

**Comment by pgsandstrom** [comment]
I've improved the sorting. While fixing it I also found that the barony flagship repaired at end of combat round instead of beginning, so now your example battle should also have damaged flagships in the detailed view :)
